#!/usr/bin/env python3
"""
mirror_instructions.py

Walk the bootstrap command folder, extract the `instructions_md` field from
every YAML file, and write a Markdown mirror per YAML into the mirrors/
subfolder. Mirror filenames are prefixed with the command's execution-phase
number so that lexicographic sort matches actual run order.

Source root: parent of this script (the bootstrap/ folder).
Mirror root: the folder this script lives in (bootstrap/mirrors/).

Prefix scheme
-------------
- manifest.yaml                 -> 00_manifest.md            (the index, always first)
- any YAML listed in manifest's `commands` map uses its `phase` value:
    bootstrap-start             -> 1.0_bootstrap-start.md
    bootstrap-ingest            -> 1.1_bootstrap-ingest.md
    bootstrap-audit             -> 1.2_bootstrap-audit.md
    bootstrap-init              -> 1.3_bootstrap-init.md
    bootstrap-checkpoint        -> 2.4_bootstrap-checkpoint.md
    bootstrap-finalize          -> 3.5_bootstrap-finalize.md
- any YAML not in the manifest  -> ZZ_<stem>.md              (sorts last)

Behavior
--------
- YAMLs without an `instructions_md` field are reported as skipped.
- YAMLs that fail to parse are reported as failed; script exits 1.
- Existing auto-generated mirrors (identified by the AUTO-GENERATED header
  in their first line) are removed before regeneration so renames and
  deletions in the source tree do not leave stale mirrors behind. Any
  user-authored .md without that header is left untouched.
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

try:
	import yaml
except ImportError:
	print("FATAL: PyYAML is not installed in the active Python.", file=sys.stderr)
	print("       Install with: pip install pyyaml", file=sys.stderr)
	sys.exit(2)


SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE_ROOT = SCRIPT_DIR.parent
MIRROR_ROOT = SCRIPT_DIR
SELF_NAME = Path(__file__).name
AUTOGEN_MARKER = "AUTO-GENERATED FROM"
MANIFEST_PREFIX = "00"
UNKNOWN_PREFIX = "ZZ"


class ParseError(Exception):
	pass


def discover_yamls(root: Path) -> list[Path]:
	"""Return all .yaml files under root, excluding anything inside the mirror tree."""
	out: list[Path] = []
	mirror_resolved = MIRROR_ROOT.resolve()
	for p in root.rglob("*.yaml"):
		try:
			p.resolve().relative_to(mirror_resolved)
			continue
		except ValueError:
			pass
		out.append(p)
	return sorted(out)


def load_phase_map() -> dict[str, str]:
	"""Build {source_filename: phase_string} from manifest.yaml. Empty dict if missing/unreadable."""
	manifest_path = SOURCE_ROOT / "manifest.yaml"
	if not manifest_path.exists():
		return {}
	try:
		with open(manifest_path, "r", encoding="utf-8") as fh:
			m = yaml.safe_load(fh)
	except (yaml.YAMLError, OSError):
		return {}
	if not isinstance(m, dict):
		return {}
	out: dict[str, str] = {}
	commands = m.get("commands") or {}
	if isinstance(commands, dict):
		for cmd_data in commands.values():
			if not isinstance(cmd_data, dict):
				continue
			f = cmd_data.get("file")
			phase = cmd_data.get("phase")
			if f and phase is not None:
				out[str(f)] = str(phase)
	return out


def order_prefix(source_filename: str, phase_map: dict[str, str]) -> str:
	if source_filename == "manifest.yaml":
		return MANIFEST_PREFIX
	return phase_map.get(source_filename, UNKNOWN_PREFIX)


def cleanup_old_mirrors() -> int:
	"""Remove any .md file under mirror root whose first line contains the autogen marker."""
	removed = 0
	for md in MIRROR_ROOT.rglob("*.md"):
		try:
			with open(md, "r", encoding="utf-8") as fh:
				first_line = fh.readline()
		except OSError:
			continue
		if AUTOGEN_MARKER in first_line:
			try:
				md.unlink()
				removed += 1
			except OSError:
				pass
	return removed


def extract_instructions(yaml_path: Path) -> str | None:
	"""Return instructions_md string, None if absent/empty. Raise ParseError on YAML parse failure."""
	try:
		with open(yaml_path, "r", encoding="utf-8") as fh:
			data = yaml.safe_load(fh)
	except yaml.YAMLError as e:
		raise ParseError(str(e))
	except OSError as e:
		raise ParseError(f"read error: {e}")
	if not isinstance(data, dict):
		return None
	val = data.get("instructions_md")
	if val is None or not isinstance(val, str) or not val.strip():
		return None
	return val


def write_mirror(source: Path, body: str, timestamp: str, phase_map: dict[str, str]) -> Path:
	rel = source.relative_to(SOURCE_ROOT)
	prefix = order_prefix(rel.name, phase_map)
	new_name = f"{prefix}_{rel.stem}.md"
	mirror_path = MIRROR_ROOT / rel.parent / new_name
	mirror_path.parent.mkdir(parents=True, exist_ok=True)
	header = (
		f"<!-- {AUTOGEN_MARKER} {rel.as_posix()} ON {timestamp}. "
		f"DO NOT EDIT THIS FILE. -->\n"
		f"<!-- Edit the `instructions_md` block in the source YAML and re-run "
		f"`mirror_instructions.bat` to regenerate. -->\n\n"
	)
	mirror_path.write_text(header + body.rstrip() + "\n", encoding="utf-8")
	return mirror_path


def fmt_path(p: Path) -> str:
	try:
		return p.relative_to(SOURCE_ROOT).as_posix()
	except ValueError:
		return str(p)


def main() -> int:
	timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
	phase_map = load_phase_map()
	removed = cleanup_old_mirrors()
	yamls = discover_yamls(SOURCE_ROOT)

	written: list[tuple[Path, Path]] = []
	skipped: list[Path] = []
	failed: list[tuple[Path, str]] = []

	for src in yamls:
		try:
			body = extract_instructions(src)
		except ParseError as e:
			failed.append((src, str(e)))
			continue
		if body is None:
			skipped.append(src)
			continue
		mirror = write_mirror(src, body, timestamp, phase_map)
		written.append((src, mirror))

	print()
	print(f"=== {SELF_NAME} @ {timestamp} ===")
	print(f"source root        : {SOURCE_ROOT}")
	print(f"mirror root        : {MIRROR_ROOT}")
	print(f"phase map entries  : {len(phase_map)}")
	print(f"old mirrors removed: {removed}")
	print(f"yamls scanned      : {len(yamls)}")
	print(f"mirrors written    : {len(written)}")
	print(f"skipped (no md)    : {len(skipped)}")
	print(f"failed             : {len(failed)}")

	if written:
		print()
		print("WRITTEN")
		for src, mirror in sorted(written, key=lambda t: fmt_path(t[1])):
			print(f"  {fmt_path(src):40}  ->  {fmt_path(mirror)}")
	if skipped:
		print()
		print("SKIPPED (no instructions_md field, or empty)")
		for src in skipped:
			print(f"  {fmt_path(src)}")
	if failed:
		print()
		print("FAILED (YAML parse / read error)")
		for src, err in failed:
			print(f"  {fmt_path(src)} :: {err}")

	return 0 if not failed else 1


if __name__ == "__main__":
	sys.exit(main())
